---

- name: Get user home directory
  set_fact:
    passwordstore_user_home: "{{ passwordstore_user_home | expanduser }}"

- name: Fail if none is found
  ansible.builtin.fail:
    msg: "Unable to find home-directory for '{{ passwordstore_user_name }}'"
  when: passwordstore_user_home | length == 0

- name: Create password-store directory
  ansible.builtin.file:
    path: "{{ passwordstore_user_home }}/.password-store"
    state: directory
    owner: "{{ passwordstore_user_name }}"
    group: "{{ passwordstore_group_name }}"
    mode: "0700"

- name: Define passwordstore_home
  ansible.builtin.set_fact:
    passwordstore_home: "{{ passwordstore_user_home }}/.password-store"
