---

- name: Install package dependencies
  ansible.builtin.package:
    name: "{{ passwordstore_dependencies }}"
    state: present
  become: yes

- name: Get installed version
  ansible.builtin.shell: |
    set -o pipefail
    pass --version | awk '/v[12]\./ {print $2}' | sed "s/^v//"
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: false
  register: __pass_version

- name: Install password-store
  ansible.builtin.include_tasks:
    file: install-{{ passwordstore_source }}.yml
