---

- name: Check assertions
  ansible.builtin.assert:
    that:
      - passwordstore_var_name is defined
      - passwordstore_secret_name is defined

- name: Set password-store home
  ansible.builtin.include_tasks:
    file: home.yml
  when: passwordstore_home is undefined

- name: Load secret '{{ passwordstore_secret_name }}' from passwordstore  # noqa name[template]
  ansible.builtin.set_fact:
    "{{ passwordstore_var_name }}": "{{ lookup('passwordstore', passwordstore_secret_name + ' returnall=true missing=empty') }}"
  vars:
    passwordstore: "{{ passwordstore_home }}"
