---

- name: Check assertions
  ansible.builtin.assert:
    that:
      - passwordstore_secret_name is defined
      - passwordstore_secret_value is defined

- name: Set password-store home
  ansible.builtin.include_tasks:
    file: home.yml
  when: passwordstore_home is undefined

- name: Load secret '{{ passwordstore_secret_name }}' from passwordstore  # noqa name[template]
  ansible.builtin.set_fact:
    __secret: "{{ lookup('passwordstore', passwordstore_secret_name + ' returnall=true missing=empty') }}"
  environment:
    PASSWORD_STORE_DIR: "{{ passwordstore_home }}"

- name: Save secret '{{ passwordstore_secret_name }}' to passwordstore  # noqa name[template]
  ansible.builtin.shell: |
    pass insert --multiline {{ passwordstore_secret_name }} <<EOF
    {{ passwordstore_secret_value }}
    EOF
  changed_when: true
  delegate_to: localhost
  become: no
  environment:
    PASSWORD_STORE_DIR: "{{ passwordstore_home }}"
  when: __secret != passwordstore_secret_value
