---

- name: Check assertions
  ansible.builtin.assert:
    that:
      - passwordstore_secret_name is defined
      - passwordstore_secret_value is defined

- name: Load secret from passwordstore
  ansible.builtin.set_fact:
    __secret: "{{ lookup('passwordstore', passwordstore_secret_name + ' returnall=true missing=empty') }}"

- name: Save secret to passwordstore
  ansible.builtin.shell: |
    pass insert --multiline {{ passwordstore_secret_name }} <<EOF
    {{ passwordstore_secret_value }}
    EOF
  changed_when: true
  delegate_to: localhost
  become: no
  when: __secret != passwordstore_secret_value
